version: 2

.job_template: &job_template
  machine:
    enabled: true
  steps:
    - checkout
    - run:
        command: |
          cd "${BASEDIR:-.}/${CIRCLE_JOB}"
          [[ $IMAGE != *"/"* ]] && IMAGE="pihole/${IMAGE}"
          [[ $IMAGE != *":"* ]] && IMAGE="${IMAGE}:$CIRCLE_JOB"
          [[ $IMAGE == *"qemu"* ]] && sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
          sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
          echo "Building $IMAGE"
          sudo docker build --pull -t $IMAGE .
          [[ "$CIRCLE_PR_NUMBER" == "" ]] && sudo docker push $IMAGE


jobs:
  debian-base:
    <<: *job_template
    environment:
      IMAGE: "debian-base:latest"

  arm:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"

  arm-qemu:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"

  armhf:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"

  aarch64:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"

  x86_64:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"

  x86_64-musl:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"

  x86_32:
    <<: *job_template
    environment:
      BASEDIR: "ftl-build"
      IMAGE: "ftl-build"


workflows:
  version: 2
  build:
    jobs:
      - debian-base:
          filters:
            tags:
              only: /^v.*/
      - arm:
          filters:
            tags:
              only: /^v.*/
      - arm-qemu:
          filters:
            tags:
              only: /^v.*/
      - armhf:
          filters:
            tags:
              only: /^v.*/
      - aarch64:
          filters:
            tags:
              only: /^v.*/
      - x86_64:
          filters:
            tags:
              only: /^v.*/
      - x86_64-musl:
          filters:
            tags:
              only: /^v.*/
      - x86_32:
          filters:
            tags:
              only: /^v.*/
