name: Image Builds

on:
  push:
  schedule:
    # 2:30am UTC every Sunday, has no particular meaning
    - cron: '30 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install docker-compose 1.25.4 (`ubuntu-latest` currently has 1.22)
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" \
                    -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Images
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker-compose pull
          docker-compose build --pull --parallel

      - name: Docker login
        run: sudo docker login --username=${{ secrets.DOCKERHUB_USER }} --password=${{ secrets.DOCKERHUB_PASS }}

      - name: Tag and push all images
        run: ./tag-and-push.sh
